### ISSUE TITLE
Color para Chocolate 

### ISSUE THREAD

**Issue by EmaVizard** [calamaris/mabaker15#2]
no esta cargando la gama de colores en la ficha

**Comment by oscarCrespo** [comment]
No comprendo bien el problema, yo abri el producto y si lo muestra y le doy click y me lo abre en una pagina aparte esta correcto? 
![captura_de_pantalla_060315_011744_am](https://cloud.githubusercontent.com/assets/6679532/7953780/5b4c1344-098e-11e5-8713-209ea706376f.jpg)

**Comment by EmaVizard** [comment]
es en la pagina q esta arriba en la que sale el link roto 
![sin-ti](https://cloud.githubusercontent.com/assets/12676061/7963866/78725db0-09da-11e5-9d2c-b37c41cc64ea.jpg)

**Comment by oscarCrespo** [comment]
Ya quedo resuelto, el problema era que el archivo es colorChocolate.jpg y estaba como ColorChocolate.jpg siempre pasa eso haha lo que pasa es que chrome cuando estas en local es medio buena onda y te da chance de que si se te fue una mayuscula pero lo demas coincide pone la imagen, pero ya en servidor ahi si truena.
